[package]
name = "mom-rpc"
version = "0.4.0"
edition = "2021"
authors = ["John Basrai"]
description = "Transport-agnostic async RPC over message-oriented middleware (MQTT, in-memory)"
license = "MIT"
repository = "https://github.com/JohnBasrai/mom-rpc"
keywords = ["pubsub", "rpc", "iot", "async"]
categories = ["network-programming", "asynchronous"]
readme = "README.md"
documentation = "https://docs.rs/mom-rpc"

[dependencies]
anyhow            = "1.0"
async-trait       = "0.1"
bytes             = { version = "1", features = ["serde"] }
log               = { version = "0.4", optional = true }
mqtt-async-client = { version = "0.3", optional = true }
rumqttc           = { version = "0.24", optional = true }
serde             = { version = "1", features = ["derive", "rc"] }
serde_json        = "1"
thiserror         = "2"
tokio             = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
uuid              = { version  = "1.11", features = ["v4", "serde"] }

[dev-dependencies]
env_logger = "0.11"
futures = "0.3.31"
tokio = { version = "1", features = ["signal"] }
tokio-test = "0.4"

[[example]]
name = "math_server"
path = "examples/math_server.rs"

[[example]]
name = "math_client"
path = "examples/math_client.rs"

[features]
default = ["logging"]
logging = ["log"]
transport_mqttac = ["mqtt-async-client"]
transport_rumqttc = ["rumqttc"]

[lints.clippy]
uninlined-format-args = "warn"
